networks:
  watchtower-network:
    driver: bridge

services:
  watchtower:
    image: containrrr/watchtower
    networks:
      - watchtower-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # Connect to Docker Daemon
      - /etc/localtime:/etc/localtime:ro            # Sync time with host
    environment:
      - WATCHTOWER_NOTIFICATIONS=email                                                          # Enable email notifications
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_NOTIFICATION_EMAIL_FROM}                # Sender email address
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}                    # Recipient email address
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}            # SMTP server address
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_NOTIFICATION_EMAIL_PORT}         # SMTP server port
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_NOTIFICATION_EMAIL_USER}         # SMTP username
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_NOTIFICATION_EMAIL_PASSWORD} # SMTP password
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=${WATCHTOWER_NOTIFICATION_EMAIL_DELAY}              # Delay to batch notifications
    command:
      - --cleanup=true                                      # Remove old images after updating
      - --remove-volumes                                    # Remove old anonymous volumes after updating
      - --label-enable=true                                 # Enable label-based updating
      - --rolling-restart                                   # Restart services one at a time
      - --interval=${WATCHTOWER_CHECK_INTERVAL_SECONDS}     # Check for container updates every x seconds
    healthcheck:
      test: ["CMD", "/watchtower", "--health-check"] # Command to check health
      interval: 1m                                  # Check every 1 minute
      timeout: 10s                                  # Timeout for each check
      retries: 3                                    # Mark unhealthy after 3 failures
      start_period: 30s                             # Grace period before starting checks
    restart: unless-stopped
