networks:
  watchtower-network:
    driver: bridge

services:
  watchtower:
    image: containrrr/watchtower
    networks:
      - watchtower-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # Connect to Docker Daemon
      -v /etc/localtime:/etc/localtime:ro           # Sync time with host
    command:
      - --cleanup=true                              # Remove old images after updating
      - --remove-volumes                            # Remove old anonymous volumes after updating
      - --label-enable=true                         # Enable label-based updating
      - --rolling-restart                           # Restart services one at a time
      - --interval=3600                             # Check for container updates every x seconds
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/watchtower", "--health-check"] # Command to check health
      interval: 1m                                  # Check every 1 minute
      timeout: 10s                                  # Timeout for each check
      retries: 3                                    # Mark unhealthy after 3 failures
      start_period: 30s                             # Grace period before starting checks